defaultEntryPoints = ["https", "http"]
logLevel = "ERROR"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
    permanent = true
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"

[docker]
exposedByDefault = false
domain = "piratenpartei.ch"

[acme]
email = "admin@piratenpartei.ch"
storage = "/var/lib/traefik/acme.json"
entryPoint = "https"
acmeLogging = true
onHostRule = true

[acme.httpChallenge]
  entryPoint = "http"
