- name: Restic Cron dir
  become: true
  file:
    path: /var/srv/restic
    recurse: yes
    state: directory

- name: Restic Cron
  become: true
  copy:
    src: files/restic.cron
    dest: /var/srv/restic/restic.cron
    mode: '0644'

- name: Restic init repo test
  become: true
  docker_container:
    image: "restic/restic"
    name: "restic-test"
    state: started
    pull: True
    auto_remove: yes
    command: "snapshots"
    volumes:
      - /var/srv:/data
    env:
      AWS_ACCESS_KEY_ID="{{ lookup('hashi_vault', 'secret=secret/duplicity/aws-access-key-id:value') }}"
      AWS_SECRET_ACCESS_KEY="{{ lookup('hashi_vault', 'secret=secret/duplicity/aws-secret-access-key:value') }}"
      RESTIC_CACHE_DIR="/root/.cache/restic"
      RESTIC_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/duplicity/passphrase:value') }}"
      RESTIC_REPOSITORY="s3:sos-ch-gva-2.exo.io/pps-backup-2"
      SOURCE_PATH="/data"
  register: restic_init
  ignore_errors: true

- name: Restic init repo
  become: true
  docker_container:
    image: "restic/restic"
    name: "restic-init"
    state: started
    pull: True
    auto_remove: yes
    command: "init"
    volumes:
      - /var/srv:/data
    env:
      AWS_ACCESS_KEY_ID="{{ lookup('hashi_vault', 'secret=secret/duplicity/aws-access-key-id:value') }}"
      AWS_SECRET_ACCESS_KEY="{{ lookup('hashi_vault', 'secret=secret/duplicity/aws-secret-access-key:value') }}"
      RESTIC_CACHE_DIR="/root/.cache/restic"
      RESTIC_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/duplicity/passphrase:value') }}"
      RESTIC_REPOSITORY="s3:sos-ch-gva-2.exo.io/pps-backup-2"
      SOURCE_PATH="/data"
  when: restic_init is failed

- name: Restic backup service
  become: true
  docker_container:
    image: "restic/restic"
    name: "restic"
    state: started
    pull: True
    restart_policy: always
    entrypoint: ""
    command: 'busybox crond -f -l 0 -L /dev/stdout'
    hostname: "restic.{{ ansible_hostname }}"
    volumes:
      - /var/srv:/data:z
      - /var/srv/restic/restic.cron:/var/spool/cron/crontabs/root:ro,Z
    env:
      AWS_ACCESS_KEY_ID="{{ lookup('hashi_vault', 'secret=secret/duplicity/aws-access-key-id:value') }}"
      AWS_SECRET_ACCESS_KEY="{{ lookup('hashi_vault', 'secret=secret/duplicity/aws-secret-access-key:value') }}"
      RESTIC_CACHE_DIR="/root/.cache/restic"
      RESTIC_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/duplicity/passphrase:value') }}"
      RESTIC_REPOSITORY="s3:sos-ch-gva-2.exo.io/pps-backup-2"
      SOURCE_PATH="/data"
