- name: Traefik config
  become: true
  copy:
    src: files/traefik.toml
    dest: /etc/traefik.toml

- name: Traefik
  docker_container:
    image: "traefik:maroilles"
    restart_policy: always
    pull: True
    name: "traefik"
    ports: "80:80,443:443"
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/traefik.toml:/traefik.toml
      - /var/lib/traefik:/var/lib/traefik
