     - name: start mysql container
       docker_container:
         image: "mysql:5"
         name: "press-crm-mysql"
         state: started
         pull: True
         volumes:
           - /data/press-crm/mysql:/var/lib/mysql
           - /data/press-crm/mysql-initdb:/docker-entrypoint-initdb.d
         env:
           MYSQL_ROOT_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/mysql/root:value') }}"
           MYSQL_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/press-crm/mysql/user:value') }}"
           MYSQL_USER="press-crm"
           MYSQL_DATABASE="press-crm"

     - name: start civicrm container
       docker_container:
         image: ppschweiz/wordpress
         name: "press-crm"
         labels:
          "traefik.enable": "true"
         state: started
         pull: True
         links:
           - press-crm-mysql:mysql
         volumes:
           - /data/press-crm/wordpress:/var/www/html
         env:
           WORDPRESS_DB_NAME="press-crm"
           WORDPRESS_DB_USER="press-crm"
           WORDPRESS_DB_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/press-crm/mysql/user:value') }}"
