- name: api
  docker_container:
    labels:
      "traefik.enable": "true"
    image: "ppschweiz/pps-api"
    name: "api"
    state: started
    pull: True
    env:
      CIVICRM_SERVER=https://members-crm.piratenpartei.ch
      PPSAPI_SECRETS="{{ lookup('hashi_vault', 'secret=secret/api/PPSAPI_SECRETS') }}"
      STRIPE_SECRET_KEY="{{ lookup('hashi_vault', 'secret=secret/api/STRIPE_SECRET_KEY') }}"
      BITPAY_PRIVKEY="{{ lookup('hashi_vault', 'secret=secret/api/BITPAY_PRIVKEY') }}"
      CIVICRM_SITE_KEY="{{ lookup('hashi_vault', 'secret=secret/api/CIVICRM_SITE_KEY') }}"
      CIVICRM_API_KEY="{{ lookup('hashi_vault', 'secret=secret/api/CIVICRM_API_KEY') }}"
      PPSAPI_BASEURL=https://api.piratenpartei.ch/api/v1
      PPSAPI_PAYLINKURL=https://www.piratenpartei.ch
      BITPAY_MODE=prod
      LATEX_URL="http://sharelatex:81"
      PPSAPI_URL="https://api.piratenpartei.ch"
      PPSAPI_PAYSECRET="{{ lookup('hashi_vault', 'secret=secret/api/PPSAPI_PAYSECRET') }}"
      PPSAPI_INVOICESECRET="{{ lookup('hashi_vault', 'secret=secret/api/PPSAPI_INVOICESECRET') }}"
