- name: press-crm
     - name: start mysql container
       docker_container:
         image: "mysql:5"
         name: "presscrm-mysql"
         state: started
         pull: True
         volumes:
           - /data/presscrm/mysql:/var/lib/mysql
         env:
           MYSQL_ROOT_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/mysql/root:value') }}"
           MYSQL_PASSWORD="{{ lookup('hashi_vault', 'secret=secret/presscrm/mysql/user:value') }}"
           MYSQL_USER="{{ lookup('hashi_vault', 'secret=secret/presscrm/mysql/password:value') }}"
           MYSQL_DATABASE="press-crm"
