- name: Create Proxy/Traefik network
  become: true
  docker_network:
    name: net-proxy

- name: Traefik config
  become: true
  copy:
    src: files/traefik.toml
    dest: /var/srv/traefik/traefik.toml
    mode: '0644'

- name: Traefik
  become: true
  docker_container:
    image: "traefik:maroilles"
    restart_policy: always
    pull: True
    name: "traefik"
    ports:
      - "[::]:443:443"
      - "0.0.0.0:443:443"
      - "[::]:80:80"
      - "0.0.0.0:80:80"
    networks:
      - name: net-proxy
    state: started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:z
      - /var/srv/traefik/traefik.toml:/traefik.toml:ro,Z
      - /var/srv/traefik/acme.json:/var/lib/traefik/acme.json:Z
    env:
      GODEBUG=tls13=1
