- name: Docker configuration
  hosts: coreos
  tasks:
    - include: container-traefik.yaml
    - include: container-api.yaml
    - include: container-press-crm.yaml
    - include: container-members-crm.yaml
    - include: container-mumble.yaml
    - include: container-backup.yaml
    - include: container-projects.yaml
    - include: container-otrs.yaml
