- include: users.yaml
- name: Piratenpartei Infra
  hosts: all
  tasks:
    - name: Start docker
      become: True
      service:
        name: docker
        state: started

    - name: pull nginx docker image
      docker_image:
        name: nginx
        tag: 1.13.0
        state: present

    - name: launch nginx container
      docker_container:
        image: "traefik"
        name: "traefik"
        ports: "80:80"
        state: started
        command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /dev/null:/traefik.toml
