- name: Create Users
  hosts: coreos
  tasks:
    - name: deploy public key JFA
      authorized_key:
        key: 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIRAzjzasfdfp6sRL9fJgTufLy0TbnQs/YR6di0iIpd3lhebLgoT8JFdVoijNlK7vENGoAUW1IeUPJilpEaCVF0= jfader@fader-t510'
        user: core
    - name: deploy public key hug
      authorized_key:
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCn4XCDsbu85OccehXtYURPpha5/IQqsjuveElCxkzIe0zNmN6KlXZf89pzARiHS251lKWXnvyQPZd9ABhcGy4VrsmXOnDVPNvx+iYyCFCNl8joZyqg7MU5B7ByofektxJmE8uZusP7WyHnUnyeF8nHg/qCdNWAZb/WjGLq5JyhgKfvHsRQFbtZfagj8VGxP4pO8OD4kvMbCLfNUncae5SHeL1smNuHNCrpRgRNir7QRuRpLjk40IMNA+hw/s1a75CgfKVhv57pYsaBE/JiWeI0RocOxV/EI9cogpyrMKeLEQg9I8FvbbJu4V98NJByD9Ecu4O2nRnRfOW1edeMr+A5 hugtest@unknown'
        user: core
    - name: deploy public key lukas
      authorized_key:
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCPA+PFV1AxwI6O0ZI3Mc4jSmTUO+ze/I8OVFSxPnw2JZjQhg9Exu0W2Fs30LboHsFrvZv95XkBhykwJMqSlSzNBUmB/8yoGYBkWG3VY8ZSSkbDfd420wBIfbRKH7iyGI7VMXE5jSWJ5/25PHfV8KdhT0PTh/gkbJvoT8EjZaVnvS/gMZtkvxpq78QrjXihQC7z7HIH2GuPtyWAGavNrRioB4mGiWni/RKUmpvPOoPdoHX/TNLWNObG16KNIce0xevDCf0fby439L1/vyoYjlFMachLszXjfBdCwy4lYLaWAq3G4xmuBkGk3eqksT8zrSb9KNfJ57GP3dJPJCz7UFh'
        user: core
    - name: deploy public key J0WI
      authorized_key:
        key: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILKISI55eX0kPjM3CnMAJd8eeS5omqaC5WKLFEKikWZC'
        user: core
