- name: Create Users
  hosts: coreos
  tasks:
    - name: deploy public key JFA
      authorized_key:
        key: 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIRAzjzasfdfp6sRL9fJgTufLy0TbnQs/YR6di0iIpd3lhebLgoT8JFdVoijNlK7vENGoAUW1IeUPJilpEaCVF0= jfader@fader-t510'
        user: core
    - name: deploy public key hug
      authorized_key:
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCn4XCDsbu85OccehXtYURPpha5/IQqsjuveElCxkzIe0zNmN6KlXZf89pzARiHS251lKWXnvyQPZd9ABhcGy4VrsmXOnDVPNvx+iYyCFCNl8joZyqg7MU5B7ByofektxJmE8uZusP7WyHnUnyeF8nHg/qCdNWAZb/WjGLq5JyhgKfvHsRQFbtZfagj8VGxP4pO8OD4kvMbCLfNUncae5SHeL1smNuHNCrpRgRNir7QRuRpLjk40IMNA+hw/s1a75CgfKVhv57pYsaBE/JiWeI0RocOxV/EI9cogpyrMKeLEQg9I8FvbbJu4V98NJByD9Ecu4O2nRnRfOW1edeMr+A5 hugtest@unknown'
        user: core
    - name: deploy public key exception
      authorized_key:
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDs1+r+w22vy1/pkr4w+UoXV3W/IfiYri1OQxQnnzn2eF5R50O6lx3FgHbYrLB7sDdHSvKbEACyw48yN9bLS4ejTvpKeRRmi/Ub1rj6TGVQrJ/KlG13+HnUKSpWQ+8ePNEAAdJejc1eue1tTo2xMn/o3IkwU0sagz0wZIgTRAL1bPGgpM1m0XsF1dGf3m7DERTGfn1La/KuxaoiFEPfktLL+eaCvEybZgeU8gmc51WFnzsOTAAiLJKrVfJ7IjXiLsbX19aWI+xVkWmOEzVtuAjhRGrLO72f+TRSUHoFl/b7vy6pNT+JtJ8Hk9hNjOILGPjWQ7f2KPlqirfKmUEyoYr3rIrNq8R81hpfoQ7hZLoi30O8zRyBbnZlVYPzicpO/3b+tVBNvh1DQ8iLfpJi5vZmSyRtjF7475kaLrYH2sfhj7rCrvl34IKHoag0C4wKzyHWzAAQPggAp0JnauifUGUMRhRZ/cp2L+586eNtmvmvqrMjEQsYTUGPT5kRQtA4ELa889MLYy2Hv5FAueqmOOdEO5F+ZQ4ec85431ZNOr7Eg8PQjFGzwxfWp9RMqkA8HX6w8L8t+PT/YM4RtEG+D4NrSvSUXIY9tFLm6A6/fKH2KQ3EIU5CvdLqPpxXv+kgRh+EQzDCE+lXR3q1a6jE8Et7CHPKZx5D7Ue9dbiwAf9Tw== cardno:0005000053A0'
        user: core
    - name: deploy public key lukas
      authorized_key:
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCPA+PFV1AxwI6O0ZI3Mc4jSmTUO+ze/I8OVFSxPnw2JZjQhg9Exu0W2Fs30LboHsFrvZv95XkBhykwJMqSlSzNBUmB/8yoGYBkWG3VY8ZSSkbDfd420wBIfbRKH7iyGI7VMXE5jSWJ5/25PHfV8KdhT0PTh/gkbJvoT8EjZaVnvS/gMZtkvxpq78QrjXihQC7z7HIH2GuPtyWAGavNrRioB4mGiWni/RKUmpvPOoPdoHX/TNLWNObG16KNIce0xevDCf0fby439L1/vyoYjlFMachLszXjfBdCwy4lYLaWAq3G4xmuBkGk3eqksT8zrSb9KNfJ57GP3dJPJCz7UFh'
        user: core
